# Generated by Django 2.0.7 on 2018-07-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id_base', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candles',
            fields=[
                ('id_candles', models.BigIntegerField(primary_key=True, serialize=False)),
                ('open', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('base_id_base', models.ForeignKey(db_column='base_id_base', on_delete=django.db.models.deletion.DO_NOTHING, to='crawlerData.Base')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id_market', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id_symbol', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('active', models.BooleanField(default=True)),
                ('market_id_market', models.ForeignKey(db_column='market_id_market', on_delete=django.db.models.deletion.DO_NOTHING, to='crawlerData.Market')),
            ],
        ),
        migrations.AddField(
            model_name='candles',
            name='market_id_market',
            field=models.ForeignKey(db_column='market_id_market', on_delete=django.db.models.deletion.DO_NOTHING, to='crawlerData.Market'),
        ),
        migrations.AddField(
            model_name='candles',
            name='symbol_id_symbol',
            field=models.ForeignKey(db_column='symbol_id_symbol', on_delete=django.db.models.deletion.DO_NOTHING, to='crawlerData.Symbol'),
        ),
    ]
