# Generated by Django 2.0.7 on 2018-07-30 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol_Base',
            fields=[
                ('id_symbol_base', models.AutoField(primary_key=True, serialize=False)),
                ('market_id_market', models.ForeignKey(db_column='market_id_market', on_delete=django.db.models.deletion.DO_NOTHING, to='crawlerData.Market')),
                ('symbol_id_symbol', models.ForeignKey(db_column='symbol_id_symbol', on_delete=django.db.models.deletion.DO_NOTHING, to='crawlerData.Symbol')),
            ],
        ),
    ]
